// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: examples/naive_chain/pkg/chain/proto/consensus.proto

package proto

import (
	smartbftprotos "github.com/hyperledger-labs/SmartBFT/smartbftprotos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsensusMessageRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	FromNode      uint64                  `protobuf:"varint,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        uint64                  `protobuf:"varint,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	Message       *smartbftprotos.Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusMessageRequest) Reset() {
	*x = ConsensusMessageRequest{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessageRequest) ProtoMessage() {}

func (x *ConsensusMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusMessageRequest.ProtoReflect.Descriptor instead.
func (*ConsensusMessageRequest) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *ConsensusMessageRequest) GetFromNode() uint64 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

func (x *ConsensusMessageRequest) GetToNode() uint64 {
	if x != nil {
		return x.ToNode
	}
	return 0
}

func (x *ConsensusMessageRequest) GetMessage() *smartbftprotos.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ConsensusMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusMessageResponse) Reset() {
	*x = ConsensusMessageResponse{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessageResponse) ProtoMessage() {}

func (x *ConsensusMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusMessageResponse.ProtoReflect.Descriptor instead.
func (*ConsensusMessageResponse) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *ConsensusMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsensusMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      uint64                 `protobuf:"varint,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        uint64                 `protobuf:"varint,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	Tx            *Transaction           `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionRequest) GetFromNode() uint64 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

func (x *TransactionRequest) GetToNode() uint64 {
	if x != nil {
		return x.ToNode
	}
	return 0
}

func (x *TransactionRequest) GetTx() *Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

type ClientTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            *Transaction           `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTransactionRequest) Reset() {
	*x = ClientTransactionRequest{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTransactionRequest) ProtoMessage() {}

func (x *ClientTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTransactionRequest.ProtoReflect.Descriptor instead.
func (*ClientTransactionRequest) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *ClientTransactionRequest) GetTx() *Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	FromNode      uint64                 `protobuf:"varint,2,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{6}
}

func (x *SyncRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SyncRequest) GetFromNode() uint64 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

type SyncResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Sequence      uint64                      `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	HasProposal   bool                        `protobuf:"varint,2,opt,name=has_proposal,json=hasProposal,proto3" json:"has_proposal,omitempty"`
	Proposal      *smartbftprotos.Proposal    `protobuf:"bytes,3,opt,name=proposal,proto3" json:"proposal,omitempty"`
	Signatures    []*smartbftprotos.Signature `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{7}
}

func (x *SyncResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SyncResponse) GetHasProposal() bool {
	if x != nil {
		return x.HasProposal
	}
	return false
}

func (x *SyncResponse) GetProposal() *smartbftprotos.Proposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *SyncResponse) GetSignatures() []*smartbftprotos.Signature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

var File_examples_naive_chain_pkg_chain_proto_consensus_proto protoreflect.FileDescriptor

const file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDesc = "" +
	"\n" +
	"4examples/naive_chain/pkg/chain/proto/consensus.proto\x12\tconsensus\x1a\x1dsmartbftprotos/messages.proto\"\x82\x01\n" +
	"\x17ConsensusMessageRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\x04R\bfromNode\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\x04R\x06toNode\x121\n" +
	"\amessage\x18\x03 \x01(\v2\x17.smartbftprotos.MessageR\amessage\"J\n" +
	"\x18ConsensusMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\":\n" +
	"\vTransaction\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"r\n" +
	"\x12TransactionRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\x04R\bfromNode\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\x04R\x06toNode\x12&\n" +
	"\x02tx\x18\x03 \x01(\v2\x16.consensus.TransactionR\x02tx\"B\n" +
	"\x18ClientTransactionRequest\x12&\n" +
	"\x02tx\x18\x01 \x01(\v2\x16.consensus.TransactionR\x02tx\"E\n" +
	"\x13TransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"F\n" +
	"\vSyncRequest\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1b\n" +
	"\tfrom_node\x18\x02 \x01(\x04R\bfromNode\"\xbe\x01\n" +
	"\fSyncResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12!\n" +
	"\fhas_proposal\x18\x02 \x01(\bR\vhasProposal\x124\n" +
	"\bproposal\x18\x03 \x01(\v2\x18.smartbftprotos.ProposalR\bproposal\x129\n" +
	"\n" +
	"signatures\x18\x04 \x03(\v2\x19.smartbftprotos.SignatureR\n" +
	"signatures2\x84\x02\n" +
	"\x10ConsensusService\x12a\n" +
	"\x14SendConsensusMessage\x12\".consensus.ConsensusMessageRequest\x1a#.consensus.ConsensusMessageResponse\"\x00\x12R\n" +
	"\x0fSendTransaction\x12\x1d.consensus.TransactionRequest\x1a\x1e.consensus.TransactionResponse\"\x00\x129\n" +
	"\x04Sync\x12\x16.consensus.SyncRequest\x1a\x17.consensus.SyncResponse\"\x002p\n" +
	"\x12TransactionService\x12Z\n" +
	"\x11SubmitTransaction\x12#.consensus.ClientTransactionRequest\x1a\x1e.consensus.TransactionResponse\"\x00BGZEgithub.com/nastya-biran/SmartBFT/examples/naive_chain/pkg/chain/protob\x06proto3"

var (
	file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescOnce sync.Once
	file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescData []byte
)

func file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP() []byte {
	file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescOnce.Do(func() {
		file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDesc), len(file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDesc)))
	})
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescData
}

var file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_examples_naive_chain_pkg_chain_proto_consensus_proto_goTypes = []any{
	(*ConsensusMessageRequest)(nil),  // 0: consensus.ConsensusMessageRequest
	(*ConsensusMessageResponse)(nil), // 1: consensus.ConsensusMessageResponse
	(*Transaction)(nil),              // 2: consensus.Transaction
	(*TransactionRequest)(nil),       // 3: consensus.TransactionRequest
	(*ClientTransactionRequest)(nil), // 4: consensus.ClientTransactionRequest
	(*TransactionResponse)(nil),      // 5: consensus.TransactionResponse
	(*SyncRequest)(nil),              // 6: consensus.SyncRequest
	(*SyncResponse)(nil),             // 7: consensus.SyncResponse
	(*smartbftprotos.Message)(nil),   // 8: smartbftprotos.Message
	(*smartbftprotos.Proposal)(nil),  // 9: smartbftprotos.Proposal
	(*smartbftprotos.Signature)(nil), // 10: smartbftprotos.Signature
}
var file_examples_naive_chain_pkg_chain_proto_consensus_proto_depIdxs = []int32{
	8,  // 0: consensus.ConsensusMessageRequest.message:type_name -> smartbftprotos.Message
	2,  // 1: consensus.TransactionRequest.tx:type_name -> consensus.Transaction
	2,  // 2: consensus.ClientTransactionRequest.tx:type_name -> consensus.Transaction
	9,  // 3: consensus.SyncResponse.proposal:type_name -> smartbftprotos.Proposal
	10, // 4: consensus.SyncResponse.signatures:type_name -> smartbftprotos.Signature
	0,  // 5: consensus.ConsensusService.SendConsensusMessage:input_type -> consensus.ConsensusMessageRequest
	3,  // 6: consensus.ConsensusService.SendTransaction:input_type -> consensus.TransactionRequest
	6,  // 7: consensus.ConsensusService.Sync:input_type -> consensus.SyncRequest
	4,  // 8: consensus.TransactionService.SubmitTransaction:input_type -> consensus.ClientTransactionRequest
	1,  // 9: consensus.ConsensusService.SendConsensusMessage:output_type -> consensus.ConsensusMessageResponse
	5,  // 10: consensus.ConsensusService.SendTransaction:output_type -> consensus.TransactionResponse
	7,  // 11: consensus.ConsensusService.Sync:output_type -> consensus.SyncResponse
	5,  // 12: consensus.TransactionService.SubmitTransaction:output_type -> consensus.TransactionResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_examples_naive_chain_pkg_chain_proto_consensus_proto_init() }
func file_examples_naive_chain_pkg_chain_proto_consensus_proto_init() {
	if File_examples_naive_chain_pkg_chain_proto_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDesc), len(file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_examples_naive_chain_pkg_chain_proto_consensus_proto_goTypes,
		DependencyIndexes: file_examples_naive_chain_pkg_chain_proto_consensus_proto_depIdxs,
		MessageInfos:      file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes,
	}.Build()
	File_examples_naive_chain_pkg_chain_proto_consensus_proto = out.File
	file_examples_naive_chain_pkg_chain_proto_consensus_proto_goTypes = nil
	file_examples_naive_chain_pkg_chain_proto_consensus_proto_depIdxs = nil
}
