// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: examples/naive_chain/pkg/chain/proto/consensus.proto

package proto

import (
	smartbftprotos "github.com/hyperledger-labs/SmartBFT/smartbftprotos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsensusMessageRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	FromNode      uint64                  `protobuf:"varint,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        uint64                  `protobuf:"varint,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	Message       *smartbftprotos.Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusMessageRequest) Reset() {
	*x = ConsensusMessageRequest{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessageRequest) ProtoMessage() {}

func (x *ConsensusMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusMessageRequest.ProtoReflect.Descriptor instead.
func (*ConsensusMessageRequest) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *ConsensusMessageRequest) GetFromNode() uint64 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

func (x *ConsensusMessageRequest) GetToNode() uint64 {
	if x != nil {
		return x.ToNode
	}
	return 0
}

func (x *ConsensusMessageRequest) GetMessage() *smartbftprotos.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ConsensusMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusMessageResponse) Reset() {
	*x = ConsensusMessageResponse{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessageResponse) ProtoMessage() {}

func (x *ConsensusMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusMessageResponse.ProtoReflect.Descriptor instead.
func (*ConsensusMessageResponse) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *ConsensusMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsensusMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      uint64                 `protobuf:"varint,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        uint64                 `protobuf:"varint,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionRequest) GetFromNode() uint64 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

func (x *TransactionRequest) GetToNode() uint64 {
	if x != nil {
		return x.ToNode
	}
	return 0
}

func (x *TransactionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TransactionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ClientTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTransactionRequest) Reset() {
	*x = ClientTransactionRequest{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTransactionRequest) ProtoMessage() {}

func (x *ClientTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTransactionRequest.ProtoReflect.Descriptor instead.
func (*ClientTransactionRequest) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *ClientTransactionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientTransactionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_examples_naive_chain_pkg_chain_proto_consensus_proto protoreflect.FileDescriptor

const file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDesc = "" +
	"\n" +
	"4examples/naive_chain/pkg/chain/proto/consensus.proto\x12\tconsensus\x1a\x1dsmartbftprotos/messages.proto\"\x82\x01\n" +
	"\x17ConsensusMessageRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\x04R\bfromNode\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\x04R\x06toNode\x121\n" +
	"\amessage\x18\x03 \x01(\v2\x17.smartbftprotos.MessageR\amessage\"J\n" +
	"\x18ConsensusMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x91\x01\n" +
	"\x12TransactionRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\x04R\bfromNode\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\x04R\x06toNode\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\"[\n" +
	"\x18ClientTransactionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"E\n" +
	"\x13TransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xc9\x01\n" +
	"\x10ConsensusService\x12a\n" +
	"\x14SendConsensusMessage\x12\".consensus.ConsensusMessageRequest\x1a#.consensus.ConsensusMessageResponse\"\x00\x12R\n" +
	"\x0fSendTransaction\x12\x1d.consensus.TransactionRequest\x1a\x1e.consensus.TransactionResponse\"\x002p\n" +
	"\x12TransactionService\x12Z\n" +
	"\x11SubmitTransaction\x12#.consensus.ClientTransactionRequest\x1a\x1e.consensus.TransactionResponse\"\x00BGZEgithub.com/nastya-biran/SmartBFT/examples/naive_chain/pkg/chain/protob\x06proto3"

var (
	file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescOnce sync.Once
	file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescData []byte
)

func file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescGZIP() []byte {
	file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescOnce.Do(func() {
		file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDesc), len(file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDesc)))
	})
	return file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDescData
}

var file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_examples_naive_chain_pkg_chain_proto_consensus_proto_goTypes = []any{
	(*ConsensusMessageRequest)(nil),  // 0: consensus.ConsensusMessageRequest
	(*ConsensusMessageResponse)(nil), // 1: consensus.ConsensusMessageResponse
	(*TransactionRequest)(nil),       // 2: consensus.TransactionRequest
	(*ClientTransactionRequest)(nil), // 3: consensus.ClientTransactionRequest
	(*TransactionResponse)(nil),      // 4: consensus.TransactionResponse
	(*smartbftprotos.Message)(nil),   // 5: smartbftprotos.Message
}
var file_examples_naive_chain_pkg_chain_proto_consensus_proto_depIdxs = []int32{
	5, // 0: consensus.ConsensusMessageRequest.message:type_name -> smartbftprotos.Message
	0, // 1: consensus.ConsensusService.SendConsensusMessage:input_type -> consensus.ConsensusMessageRequest
	2, // 2: consensus.ConsensusService.SendTransaction:input_type -> consensus.TransactionRequest
	3, // 3: consensus.TransactionService.SubmitTransaction:input_type -> consensus.ClientTransactionRequest
	1, // 4: consensus.ConsensusService.SendConsensusMessage:output_type -> consensus.ConsensusMessageResponse
	4, // 5: consensus.ConsensusService.SendTransaction:output_type -> consensus.TransactionResponse
	4, // 6: consensus.TransactionService.SubmitTransaction:output_type -> consensus.TransactionResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_examples_naive_chain_pkg_chain_proto_consensus_proto_init() }
func file_examples_naive_chain_pkg_chain_proto_consensus_proto_init() {
	if File_examples_naive_chain_pkg_chain_proto_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDesc), len(file_examples_naive_chain_pkg_chain_proto_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_examples_naive_chain_pkg_chain_proto_consensus_proto_goTypes,
		DependencyIndexes: file_examples_naive_chain_pkg_chain_proto_consensus_proto_depIdxs,
		MessageInfos:      file_examples_naive_chain_pkg_chain_proto_consensus_proto_msgTypes,
	}.Build()
	File_examples_naive_chain_pkg_chain_proto_consensus_proto = out.File
	file_examples_naive_chain_pkg_chain_proto_consensus_proto_goTypes = nil
	file_examples_naive_chain_pkg_chain_proto_consensus_proto_depIdxs = nil
}
